### ISSUE TITLE
Build times - MacOS - 136049 lines

### ISSUE THREAD

**Issue by anagrius** [evancz/elm-project-survey#1]
OS:  Mac OS X 10.14.5
    RAM: 16GB
    CPU: Intel® Core™ i7-6920HQ @ 2.90GHz, 4 physical cores
    PROJECT: 563 files, 136049 lines, 20 direct deps, 4 indirect deps
    ASSET SIZE: 5322837 bytes -> 1320640 bytes (minified) -> 374402 bytes (gzipped)

    COMMAND: elm make src/elm/Humio/Main.elm

      2454ms  -- from scratch
       803ms  -- worst incremental
       638ms  -- median incremental
       532ms  -- best incremental

    COMMAND: elm make src/elm/Humio/Main.elm --output=/dev/null

      2284ms  -- from scratch
       283ms  -- worst incremental
       109ms  -- median incremental
        95ms  -- best incremental

[build.log](https://github.com/evancz/elm-project-survey/files/3817219/build.log)

**Comment by evancz** [comment]
It is so exciting to see these numbers!!! Thank you for running the script and sharing the data!

I was not expecting the `--output=/dev/null` flag to make such a huge difference. Glad it's included in the data!
