### ISSUE TITLE
Build times - Mac - 61605 lines

### ISSUE THREAD

**Issue by peterszerzo** [evancz/elm-project-survey#21]
-- OVERVIEW -----------------------------------------------

    OS:  Mac OS X 10.14.6
    RAM: 8GB
    CPU: Intel® Core™ i7-3520M @ 2.90GHz, 2 physical cores
    PROJECT: 232 files, 61605 lines, 22 direct deps, 9 indirect deps
    ASSET SIZE: 2721741 bytes -> 613987 bytes (minified) -> 189426 bytes (gzipped)

    COMMAND: elm make src/studio/Studio.elm

      2155ms  -- from scratch
       664ms  -- worst incremental
       453ms  -- median incremental
       429ms  -- best incremental

    COMMAND: elm make src/studio/Studio.elm --output=/dev/null

      2059ms  -- from scratch
       181ms  -- worst incremental
        79ms  -- median incremental
        64ms  -- best incremental

**Comment by evancz** [comment]
I am going through and collecting data, but this issue does not have the `build.log` file attached. Can you rerun the script and open a new issue that contains the results in that format?

(It has a bunch of additional data about individual files. These are summarized in the print out with min/median/max, but I want to get the distribution as well.)

Sorry for the inconvenience!

**Comment by peterszerzo** [comment]
No worries, @evancz, I'll try to rerun sometime in the next few days.
