### ISSUE TITLE
Build times - Mac - 12127 lines

### ISSUE THREAD

**Issue by neurodynamic** [evancz/elm-project-survey#6]
-- OVERVIEW -----------------------------------------------

    OS:  Mac OS X 10.15.1
    RAM: 16GB
    CPU: Intel® Core™ i7-4870HQ @ 2.50GHz, 4 physical cores
    PROJECT: 143 files, 12127 lines, 16 direct deps, 4 indirect deps
    ASSET SIZE: 839391 bytes -> 183927 bytes (minified) -> 56203 bytes (gzipped)

    COMMAND: elm make elm/Dashboard.elm

      1064ms  -- from scratch
       201ms  -- worst incremental
       151ms  -- median incremental
       139ms  -- best incremental

    COMMAND: elm make elm/Dashboard.elm --output=/dev/null

      1023ms  -- from scratch
        98ms  -- worst incremental
        48ms  -- median incremental
        43ms  -- best incremental

-----------------------------------------------------------
[build.log](https://github.com/evancz/elm-project-survey/files/3820476/build.log)

**Comment by neurodynamic** [comment]
Note: this issue is for compiling one of the files included in this issue: https://github.com/evancz/elm-project-survey/issues/16

That issue, compiling all 6 endpoints at once is more representative of my actual use case.

**Comment by evancz** [comment]
Closing in favor of #16. Thank you!
