### ISSUE TITLE
Build times - Mac - 14376 lines

### ISSUE THREAD

**Issue by neurodynamic** [evancz/elm-project-survey#7]
-- OVERVIEW -----------------------------------------------

    OS:  Mac OS X 10.15.1
    RAM: 16GB
    CPU: Intel® Core™ i7-4870HQ @ 2.50GHz, 4 physical cores
    PROJECT: 160 files, 14376 lines, 16 direct deps, 4 indirect deps
    ASSET SIZE: 963002 bytes -> 212086 bytes (minified) -> 64553 bytes (gzipped)

    COMMAND: elm make elm/Site.elm

      1315ms  -- from scratch
       257ms  -- worst incremental
       168ms  -- median incremental
       152ms  -- best incremental

    COMMAND: elm make elm/Site.elm --output=/dev/null

      1423ms  -- from scratch
       141ms  -- worst incremental
        58ms  -- median incremental
        43ms  -- best incremental

-----------------------------------------------------------
[site-build.log](https://github.com/evancz/elm-project-survey/files/3820488/site-build.log)

**Comment by neurodynamic** [comment]
Note: this issue is for compiling one of the files included in this issue: https://github.com/evancz/elm-project-survey/issues/16

That issue, compiling all 6 endpoints at once is more representative of my actual use case.

**Comment by evancz** [comment]
Closing in favor of #16. Thank you!
